### PR TITLE
use includes instead of match

### PR DESCRIPTION
**Pull request by toadkicker**
since we want a truth-y answer using includes is a better choice than match

### CODE REVIEW

**Comment by toadkicker** [comment]
Fixes #2

**Comment by hassaku** [comment]
Thank you for your PR and sorry for late response.
Unfortunately, I could not confirm to solve the problem.
```
$ coffee --version                                                                                                                                                                                               
CoffeeScript version 1.12.2
```

```
coffee> "@robo how are you?".match(///^@? robo .*$///i)
[ '@robo how are you?', index: 0, input: '@robo how are you?' ]

coffee> "@robo how are you?".includes(///^@? robo .*$///i)
repl:1
_ = "@robo how are you?".includes(/^@?robo.*$/i);
                         ^
TypeError: First argument to String.prototype.includes must not be a regular expression
...
```

Thank you in advance for your help.

**Comment by toadkicker** [comment]
@hassaku should be ok now, seems to be working with hip chat for my group.

**Comment by hassaku** [comment]
Thank you very much.

**Pull request merged**
