### PR TITLE
Handle hipchat's double spaces between bot name and content during the input text match, and use the correct part of the message object for showing suggestions

### PR DESCRIPTION
**Pull request by Sarah-E-Greene**
Here is what is required for this plugin to work with HipChat (although I suspect the message.match => message.text.match may not work on other protocols).

From https://github.com/hassaku/hubot-suggest/issues/2

### CODE REVIEW

**Comment by hassaku** [comment]
Sorry that I cannot merge this PR for a long time. I'm concerned about regression for another adopters.

**Comment by mtscout6** [comment]
What other use cases are you thinking could be an issue? Perhaps we could write some unit tests to account for the scenarios you are concerned about.

**Comment by hassaku** [comment]
@mtscout6 
Although my use cases are for slack and kandan, it would be helpful :smile:  if someone prepares some unit tests for any adaptor. So I could add tests for my use cases in accordance with prepared tests.

**Comment by hassaku** [comment]
@SarahKowalik  I'm going to close this outdated PR. If you have a problem yet, please feel free to create issues or PRs. Thanks.

**Pull request closed without merging**
